// Shared helper functions

const buildMediaUrl = (type, path) => {
	if (type == 'image') {
		return path ? `${process.env.APP_URL}/api/media?type=${encodeURIComponent(type)}&path=${encodeURIComponent(path)}` : null;
	}

	if (type == 'audio' || type == 'video') {
		return path ? `${process.env.STREAM_URL}/api/media?type=${encodeURIComponent(type)}&path=${encodeURIComponent(path)}` : null;
	}

	return null
}

const buildStreamUrl = (streamPath) => {
	if (!streamPath) return null;

	const value = String(streamPath).trim();
	if (!value) return null;

	if (/^[a-z][a-z\d+.-]*:\/\//i.test(value)) return value;
	if (value.startsWith("//")) return `https:${value}`;

	// Older streaming records may contain a domain without its protocol.
	if (!value.includes("/") && /^[^\s.]+\.[^\s.]+$/.test(value)) {
		return `https://${value}`;
	}

	// Imported TV playlists are generated by the Laravel app on its public
	// storage disk. Keep this base separate from STREAM_URL, which belongs to
	// this service's audio/video media endpoint.
	const baseUrl = (
		process.env.TV_CHANNEL_STREAM_URL ||
		process.env.STREAM_URL ||
		process.env.APP_URL ||
		""
	).replace(/\/+$/, "");
	if (!baseUrl) return value;

	return `${baseUrl}/${value.replace(/^\/+/, "")}`;
};

// Build a QR code image URL (Google Chart API) from a target URL
const buildQrUrl = (targetUrl, size = 300) =>
	targetUrl
		? `https://chart.googleapis.com/chart?chs=${size}x${size}&cht=qr&chl=${encodeURIComponent(
				targetUrl,
			)}`
		: null;

const parseActiveFlag = (raw, defaultVal = true) => {
	if (raw === undefined) return defaultVal;
	const val = String(raw).toLowerCase();
	if (["1", "true", "yes", "on"].includes(val)) return true;
	if (["0", "false", "no", "off"].includes(val)) return false;
	return defaultVal;
};

module.exports = { buildMediaUrl, buildStreamUrl, buildQrUrl, parseActiveFlag };
